title: Allium LLM-native spec language
description: Give your AI agents something better than a prompt. Allium is a behavioural specification language for communicating intent.
baseurl: /allium
url: https://juxt.github.io
